language: ruby
matrix:
  include:
    - env: TAGS=
      rvm: 2.3.3
#   - env: TAGS=tcell
#     rvm: 2.2.0

install:
- sudo apt-get update
- sudo apt-get install -y libncurses-dev lib32ncurses5-dev libgpm-dev
- sudo add-apt-repository -y ppa:pi-rho/dev
- sudo apt-add-repository -y ppa:fish-shell/release-2
- sudo apt-get update
- sudo apt-get install -y tmux=1.9a-1~ppa1~p
- sudo apt-get install -y zsh fish

script: |
  export GOPATH=~/go
  export FZF_BASE=$GOPATH/src/github.com/junegunn/fzf

  mkdir -p $GOPATH/src/github.com/junegunn
  ln -s $(pwd) $FZF_BASE

  cd $FZF_BASE/src && make test fzf/fzf-linux_amd64 install &&
  cd $FZF_BASE/bin && ln -sf fzf-linux_amd64 fzf-$(./fzf --version)-linux_amd64 &&
  cd $FZF_BASE && yes | ./install && rm -f fzf &&
  tmux new "ruby test/test_go.rb > out && touch ok" && cat out && [ -e ok ]
