language: go
dist: xenial
addons:
  apt:
    sources:
      - sourceline: "ppa:pi-rho/dev"
      - sourceline: "ppa:fish-shell/release-2"
    packages:
    - tmux
    - zsh
    - fish

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: unittest
      go: "1.11.x"
      script: make && make test

    - stage: cli
      go: "1.11.x"
      rvm: "2.5"
      script: |
        make install && ./install --all && tmux new "ruby test/test_go.rb > out && touch ok" && cat out && [ -e ok ]

